//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMPlatform.UI.PlagiateReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.ws/", ConfigurationName="PlagiateReference.ISoapWS")]
    public interface ISoapWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LMPlatform.UI.PlagiateReference.checkResponse check(LMPlatform.UI.PlagiateReference.check request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LMPlatform.UI.PlagiateReference.checkResponse> checkAsync(LMPlatform.UI.PlagiateReference.check request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LMPlatform.UI.PlagiateReference.checkByDirectoryResponse checkByDirectory(LMPlatform.UI.PlagiateReference.checkByDirectory request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LMPlatform.UI.PlagiateReference.checkByDirectoryResponse> checkByDirectoryAsync(LMPlatform.UI.PlagiateReference.checkByDirectory request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LMPlatform.UI.PlagiateReference.checkBySingleDocResponse checkBySingleDoc(LMPlatform.UI.PlagiateReference.checkBySingleDoc request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LMPlatform.UI.PlagiateReference.checkBySingleDocResponse> checkBySingleDocAsync(LMPlatform.UI.PlagiateReference.checkBySingleDoc request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="check", WrapperNamespace="http://soap.ws/", IsWrapped=true)]
    public partial class check {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("docs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] docs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int threshold;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int termCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int mode;
        
        public check() {
        }
        
        public check(string[] docs, int threshold, int termCount, int mode) {
            this.docs = docs;
            this.threshold = threshold;
            this.termCount = termCount;
            this.mode = mode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkResponse", WrapperNamespace="http://soap.ws/", IsWrapped=true)]
    public partial class checkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public checkResponse() {
        }
        
        public checkResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkByDirectory", WrapperNamespace="http://soap.ws/", IsWrapped=true)]
    public partial class checkByDirectory {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("folders", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] folders;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int threshold;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int termCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int mode;
        
        public checkByDirectory() {
        }
        
        public checkByDirectory(string[] folders, int threshold, int termCount, int mode) {
            this.folders = folders;
            this.threshold = threshold;
            this.termCount = termCount;
            this.mode = mode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkByDirectoryResponse", WrapperNamespace="http://soap.ws/", IsWrapped=true)]
    public partial class checkByDirectoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public checkByDirectoryResponse() {
        }
        
        public checkByDirectoryResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkBySingleDoc", WrapperNamespace="http://soap.ws/", IsWrapped=true)]
    public partial class checkBySingleDoc {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string checkDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("folders", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] folders;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int threshold;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int termCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int mode;
        
        public checkBySingleDoc() {
        }
        
        public checkBySingleDoc(string checkDoc, string[] folders, int threshold, int termCount, int mode) {
            this.checkDoc = checkDoc;
            this.folders = folders;
            this.threshold = threshold;
            this.termCount = termCount;
            this.mode = mode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkBySingleDocResponse", WrapperNamespace="http://soap.ws/", IsWrapped=true)]
    public partial class checkBySingleDocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public checkBySingleDocResponse() {
        }
        
        public checkBySingleDocResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISoapWSChannel : LMPlatform.UI.PlagiateReference.ISoapWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoapWSClient : System.ServiceModel.ClientBase<LMPlatform.UI.PlagiateReference.ISoapWS>, LMPlatform.UI.PlagiateReference.ISoapWS {
        
        public SoapWSClient() {
        }
        
        public SoapWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoapWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMPlatform.UI.PlagiateReference.checkResponse LMPlatform.UI.PlagiateReference.ISoapWS.check(LMPlatform.UI.PlagiateReference.check request) {
            return base.Channel.check(request);
        }
        
        public string check(string[] docs, int threshold, int termCount, int mode) {
            LMPlatform.UI.PlagiateReference.check inValue = new LMPlatform.UI.PlagiateReference.check();
            inValue.docs = docs;
            inValue.threshold = threshold;
            inValue.termCount = termCount;
            inValue.mode = mode;
            LMPlatform.UI.PlagiateReference.checkResponse retVal = ((LMPlatform.UI.PlagiateReference.ISoapWS)(this)).check(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMPlatform.UI.PlagiateReference.checkResponse> LMPlatform.UI.PlagiateReference.ISoapWS.checkAsync(LMPlatform.UI.PlagiateReference.check request) {
            return base.Channel.checkAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMPlatform.UI.PlagiateReference.checkResponse> checkAsync(string[] docs, int threshold, int termCount, int mode) {
            LMPlatform.UI.PlagiateReference.check inValue = new LMPlatform.UI.PlagiateReference.check();
            inValue.docs = docs;
            inValue.threshold = threshold;
            inValue.termCount = termCount;
            inValue.mode = mode;
            return ((LMPlatform.UI.PlagiateReference.ISoapWS)(this)).checkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMPlatform.UI.PlagiateReference.checkByDirectoryResponse LMPlatform.UI.PlagiateReference.ISoapWS.checkByDirectory(LMPlatform.UI.PlagiateReference.checkByDirectory request) {
            return base.Channel.checkByDirectory(request);
        }
        
        public string checkByDirectory(string[] folders, int threshold, int termCount, int mode) {
            LMPlatform.UI.PlagiateReference.checkByDirectory inValue = new LMPlatform.UI.PlagiateReference.checkByDirectory();
            inValue.folders = folders;
            inValue.threshold = threshold;
            inValue.termCount = termCount;
            inValue.mode = mode;
            LMPlatform.UI.PlagiateReference.checkByDirectoryResponse retVal = ((LMPlatform.UI.PlagiateReference.ISoapWS)(this)).checkByDirectory(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMPlatform.UI.PlagiateReference.checkByDirectoryResponse> LMPlatform.UI.PlagiateReference.ISoapWS.checkByDirectoryAsync(LMPlatform.UI.PlagiateReference.checkByDirectory request) {
            return base.Channel.checkByDirectoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMPlatform.UI.PlagiateReference.checkByDirectoryResponse> checkByDirectoryAsync(string[] folders, int threshold, int termCount, int mode) {
            LMPlatform.UI.PlagiateReference.checkByDirectory inValue = new LMPlatform.UI.PlagiateReference.checkByDirectory();
            inValue.folders = folders;
            inValue.threshold = threshold;
            inValue.termCount = termCount;
            inValue.mode = mode;
            return ((LMPlatform.UI.PlagiateReference.ISoapWS)(this)).checkByDirectoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMPlatform.UI.PlagiateReference.checkBySingleDocResponse LMPlatform.UI.PlagiateReference.ISoapWS.checkBySingleDoc(LMPlatform.UI.PlagiateReference.checkBySingleDoc request) {
            return base.Channel.checkBySingleDoc(request);
        }
        
        public string checkBySingleDoc(string checkDoc, string[] folders, int threshold, int termCount, int mode) {
            LMPlatform.UI.PlagiateReference.checkBySingleDoc inValue = new LMPlatform.UI.PlagiateReference.checkBySingleDoc();
            inValue.checkDoc = checkDoc;
            inValue.folders = folders;
            inValue.threshold = threshold;
            inValue.termCount = termCount;
            inValue.mode = mode;
            LMPlatform.UI.PlagiateReference.checkBySingleDocResponse retVal = ((LMPlatform.UI.PlagiateReference.ISoapWS)(this)).checkBySingleDoc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMPlatform.UI.PlagiateReference.checkBySingleDocResponse> LMPlatform.UI.PlagiateReference.ISoapWS.checkBySingleDocAsync(LMPlatform.UI.PlagiateReference.checkBySingleDoc request) {
            return base.Channel.checkBySingleDocAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMPlatform.UI.PlagiateReference.checkBySingleDocResponse> checkBySingleDocAsync(string checkDoc, string[] folders, int threshold, int termCount, int mode) {
            LMPlatform.UI.PlagiateReference.checkBySingleDoc inValue = new LMPlatform.UI.PlagiateReference.checkBySingleDoc();
            inValue.checkDoc = checkDoc;
            inValue.folders = folders;
            inValue.threshold = threshold;
            inValue.termCount = termCount;
            inValue.mode = mode;
            return ((LMPlatform.UI.PlagiateReference.ISoapWS)(this)).checkBySingleDocAsync(inValue);
        }
    }
}
