// <auto-generated />
namespace LMPlatform.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddTinCanObjects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTinCanObjects));
        
        string IMigrationMetadata.Id
        {
            get { return "201812091219299_AddTinCanObjects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
