// <auto-generated />
namespace LMPlatform.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class IsCoursProject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsCoursProject));
        
        string IMigrationMetadata.Id
        {
            get { return "201904221345077_IsCoursProject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
